/**
 * Generates the design-system CSS from the TS token configs:
 *   - styles/theme.css      — Tailwind v4 @theme (colors, fonts, scale, shadows)
 *   - styles/typography.css — @utility text-<name> presets
 * Run with: pnpm --filter @splitsy/design-system generate
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { colors } from "../configs/colors.ts";
import { fonts, fontSize, typePresets } from "../configs/typography.ts";
import { radius, shadow } from "../configs/scale.ts";

const here = dirname(fileURLToPath(import.meta.url));
const stylesDir = join(here, "..", "styles");

const section = (title: string, entries: Record<string, string>, prefix: string) =>
  [`  /* ${title} */`, ...Object.entries(entries).map(([k, v]) => `  --${prefix}-${k}: ${v};`)].join(
    "\n",
  );

const themeCss = [
  "/* AUTO-GENERATED by scripts/generate-theme.ts — edit configs/*.ts, then regenerate. */",
  "@theme {",
  section("colors", colors, "color"),
  section("fonts", fonts, "font"),
  section("type scale", fontSize, "text"),
  section("radii", radius, "radius"),
  section("shadows", shadow, "shadow"),
  "}",
  "",
].join("\n");

const typographyCss = [
  "/* AUTO-GENERATED by scripts/generate-theme.ts — edit configs/typography.ts, then regenerate. */",
  ...Object.entries(typePresets).map(
    ([name, classes]) => `@utility text-${name} {\n  @apply ${classes};\n}`,
  ),
  "",
].join("\n\n");

mkdirSync(stylesDir, { recursive: true });
writeFileSync(join(stylesDir, "theme.css"), themeCss);
writeFileSync(join(stylesDir, "typography.css"), typographyCss);
console.log(`[design-system] wrote theme.css + typography.css to ${stylesDir}`);
