/**
 * Generates styles/theme.css (Tailwind v4 @theme) from the TS token configs.
 * Run with: pnpm --filter @splitsy/design-system generate
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { colors } from "../configs/colors.ts";
import { fonts, fontSize } from "../configs/typography.ts";
import { radius, shadow } from "../configs/scale.ts";

const here = dirname(fileURLToPath(import.meta.url));
const stylesDir = join(here, "..", "styles");
const outFile = join(stylesDir, "theme.css");

const section = (title: string, entries: Record<string, string>, prefix: string) =>
  [`  /* ${title} */`, ...Object.entries(entries).map(([k, v]) => `  --${prefix}-${k}: ${v};`)].join(
    "\n",
  );

const css = [
  "/* AUTO-GENERATED by scripts/generate-theme.ts — edit configs/*.ts, then regenerate. */",
  "@theme {",
  section("colors", colors, "color"),
  section("fonts", fonts, "font"),
  section("type scale", fontSize, "text"),
  section("radii", radius, "radius"),
  section("shadows", shadow, "shadow"),
  "}",
  "",
].join("\n");

mkdirSync(stylesDir, { recursive: true });
writeFileSync(outFile, css);
console.log(`[design-system] wrote ${outFile}`);
